language: java

jdk:
  - oraclejdk8

after_success:
  - sudo chown -R ${USER} /home/travis/build/numenta
  - mvn clean integration-test -Dmaven.test.failure.ignore=true jacoco:report coveralls:report


#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true